---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dojo
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/DanijelRadakovic/dojo
  ref:
    branch: master
---
kind: HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
metadata:
  name: dojo
  namespace: flux-system
spec:
  maxHistory: 3
  interval: 30m # run drift detection every 30 minutes
  driftDetection:
    mode: enabled # undo kubectl edits and other unintended changes
  install:
    strategy:
      name: RetryOnFailure # retry failed installations instead of uninstalling
      retryInterval: 5m # retry failed installations every five minutes
    createNamespace: true
  upgrade:
    crds: CreateReplace # update CRDs when upgrading
    strategy:
      name: RetryOnFailure # retry failed upgrades instead of rollback
      retryInterval: 5m # retry failed upgrades every five minutes
  chart:
    spec:
      chart: ./chart # path to the chart directory on dojo git repo
      sourceRef:
        kind: GitRepository
        name: dojo
        namespace: flux-system
  targetNamespace: dojo
  values:
    fullnameOverride: "dojo"
    nameOverride: "dojo"
