apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dojo
  namespace: flux-system
spec:
  values:
    extraEnvVars:
      DB_ENDPOINT: postgres-rw.dojo
      DB_PORT: 5432
      DB_NAME: dojo
      DB_USER: dojo
      DB_PASS: 7PtQTNX3nZa3qnUVXFMJHjMu7fZT9P8AoxaaHAsAu2znxizkuimLYqiEbS2Tn5g6
