apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dojo
  namespace: flux-system
spec:
  values:
    extraVolumes:
      - name: tmp
        emptyDir: { }

    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp

    workingDir: /tmp

    extraEnvVars:
      - name: DB_ENDPOINT
        value: postgres-rw
      - name: DB_PORT
        value: "5432"
      - name: DB_NAME
        value: dojo
      - name: DB_USER
        value: dojo
      - name: DB_PASS
        value: "7PtQTNX3nZa3qnUVXFMJHjMu7fZT9P8AoxaaHAsAu2znxizkuimLYqiEbS2Tn5g6"

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: dojo.192.168.49.2.nip.io  # minikube ip -p dev
      path: /
      pathType: Prefix
      extraPaths:
        - path: "/*"
          pathType: Prefix
          backend:
            service:
              name: dojo
              port:
                name: http
